# docker compose file
version: "2"
services:
  erp-authentication: 
    image: erp-authentication:0.0.1
    container_name: erp-authentication
    restart: always
    build: .
    ports: 
      - "4001:4000"
    depends_on:
      - erp-authentication-db
    environment:
      - DB_HOST=erp-authentication-db
      - DB_PORT=27017
      - DB_NAME=erp-authentication-db
  
  erp-authentication-db:
    container_name: erp-authentication-db
    image: mongo:4.0
    restart: always
    volumes:
      - ./db-data:/data/db
    ports:
      - "27029:27017"